defmodule AshSupabase.Resource do
  @supabase %Spark.Dsl.Section{
    name: :supabase,
    describe: """
    Configure how this resource's table is exposed to Supabase's other
    services (PostgREST, Realtime) once it is written through Ash.
    """,
    schema: [
      realtime?: [
        type: :boolean,
        default: true,
        doc: """
        Whether `mix ash_supabase.gen_policies` should add this resource's
        table to the `supabase_realtime` publication, so Supabase Realtime
        clients receive live change feeds for rows Ash writes. Set to
        `false` for tables that hold sensitive data no client should
        stream directly (events tables, internal-only resources, etc).
        """
      ],
      expose_via_postgrest?: [
        type: :boolean,
        default: false,
        doc: """
        Whether the `anon`/`authenticated` Postgres roles PostgREST
        connects as get *any* direct privileges on this table. Defaults
        to `false`: Row Level Security denies all direct access and the
        only way to read or write the table is through Ash (an Ash-side
        API, a generated `AshJsonApi`/`AshGraphql` endpoint, LiveView,
        etc). Set to `true` to allow direct PostgREST reads (see
        `postgrest_read_only?`) for tables that are safe as an ad-hoc
        public/authenticated read API.
        """
      ],
      postgrest_read_only?: [
        type: :boolean,
        default: true,
        doc: """
        When `expose_via_postgrest?` is `true`, whether the granted RLS
        policy is SELECT-only. Direct INSERT/UPDATE/DELETE from PostgREST
        is never generated by `AshSupabase` regardless of this setting --
        writes always go through Ash so they always produce an event.
        Setting this to `false` only changes whether *reads* also bypass
        RLS row filtering; it never opens direct writes.
        """
      ],
      rls_authenticated_select?: [
        type: :boolean,
        default: false,
        doc: """
        When `expose_via_postgrest?` is `true`, grant SELECT to the
        `authenticated` role (signed-in Supabase Auth users) in addition
        to `anon`. Ignored when `expose_via_postgrest?` is `false`.
        """
      ],
      gateway_actions: [
        type: {:list, :atom},
        default: [],
        doc: """
        Action names on this resource that `AshSupabase.Gateway` accepts
        as `{resource, action, params}` dispatch targets, and that
        `mix ash_supabase.export_ontology` (feeding
        `priv/ggen/ash-supabase-client-pack`, rendered by
        `mix ggen_igniter.sync`) emits a typed TypeScript client function
        for. This is the whole point of the dual-table/RLS lockdown: a
        write a Supabase client can actually make. Empty by default -- a
        resource must opt in explicitly to being reachable by a client
        that only knows Supabase, the same way `expose_via_postgrest?`
        must be opted into for reads.
        """
      ]
    ]
  }

  @moduledoc """
  The `AshSupabase.Resource` DSL extension.

  Add it (alongside `AshEvents.Events`) to any `Ash.Resource` backed by
  `AshPostgres.DataLayer` to mark it as a Supabase-fronted, dual-table
  event-sourced resource:

      defmodule MyApp.Todos.Todo do
        use Ash.Resource,
          otp_app: :my_app,
          domain: MyApp.Todos,
          data_layer: AshPostgres.DataLayer,
          extensions: [AshSupabase.Resource, AshEvents.Events]

        postgres do
          table "todos"
          repo MyApp.Repo
        end

        events do
          event_log MyApp.Events.Event
        end

        supabase do
          realtime? true
        end

        # attributes/actions/policies as usual...
      end

  Compilation fails with a `Spark.Error.DslError` if:

    * `data_layer` is not `AshPostgres.DataLayer` (Supabase *is* Postgres;
      there's nowhere else for the row to live), or
    * `AshEvents.Events` is not also applied, or is applied without an
      `event_log` configured.

  This is deliberate: `AshSupabase.Resource` exists to guarantee the
  dual-table event-sourcing shape, not merely to suggest it.
  """

  use Spark.Dsl.Extension,
    sections: [@supabase],
    transformers: [
      AshSupabase.Transformers.RequirePostgresDataLayer,
      AshSupabase.Transformers.RequireEventSourcing,
      AshSupabase.Transformers.RequireGatewayActionsExist
    ]
end
