defmodule Mix.Tasks.AshSupabase.GenPolicies do
  @shortdoc "Generate the RLS/Realtime migration that locks Supabase CRUD to Ash-only"

  @moduledoc """
  #{@shortdoc}.

      mix ash_supabase.gen_policies

  Introspects every domain configured for this app (`config :my_app,
  ash_domains: [...]`) and, for every resource using
  `AshSupabase.Resource` plus every `AshEvents.EventLog` resource, writes
  one idempotent Ecto migration per repo containing:

    * `ENABLE ROW LEVEL SECURITY` and `REVOKE ALL ... FROM anon,
      authenticated` for every table -- the default-deny baseline that
      makes "all Supabase CRUD goes through Ash" true at the database
      level rather than by convention.
    * A `SELECT`-only RLS policy for resources that opted in with
      `supabase do expose_via_postgrest? true end`.
    * `ALTER PUBLICATION supabase_realtime ADD TABLE ...` for resources
      with `realtime? true` (the default), so Supabase Realtime clients
      still see live changes -- they're just changes Ash made.
    * Full lockdown (no realtime, no grants) for every `AshEvents`
      event log, regardless of configuration -- the audit trail is never
      meant to be client-readable.

  Run it after `mix ash_postgres.generate_migrations`, whenever you add,
  remove, or reconfigure an `AshSupabase.Resource`, and run
  `mix ash_postgres.migrate` (or `mix ecto.migrate`) as usual afterwards.

  ## Options

    * `--dry-run` -- print the SQL instead of writing a migration file.
  """

  use Mix.Task

  alias AshSupabase.SQL

  @impl Mix.Task
  def run(argv) do
    Mix.Task.run("compile")
    Mix.Task.run("app.config")

    {opts, _argv} = OptionParser.parse!(argv, strict: [dry_run: :boolean])
    otp_app = Mix.Project.config()[:app]

    supabase_resources = AshSupabase.Info.supabase_resources(otp_app)
    event_log_resources = event_log_resources(otp_app)

    if supabase_resources == [] and event_log_resources == [] do
      Mix.shell().info("""
      No AshSupabase.Resource or AshEvents.EventLog resources found in \
      the domains configured under `config :#{otp_app}, ash_domains: [...]`. \
      Nothing to generate.
      """)
    else
      supabase_resources
      |> Enum.map(&{&1, :resource})
      |> Kernel.++(Enum.map(event_log_resources, &{&1, :event_log}))
      |> Enum.group_by(fn {resource, _kind} -> AshPostgres.DataLayer.Info.repo(resource) end)
      |> Enum.each(&generate_for_repo(&1, opts))
    end
  end

  defp generate_for_repo({repo, resources}, opts) do
    {up, down} = statements_for(resources)

    if opts[:dry_run] do
      print_dry_run(repo, up, down)
    else
      write_migration!(repo, up, down)
    end
  end

  defp statements_for(resources) do
    Enum.reduce(resources, {[], []}, fn {resource, kind}, {up, down} ->
      table = AshPostgres.DataLayer.Info.table(resource)

      %{up: res_up, down: res_down} =
        case kind do
          :resource ->
            SQL.resource_statements(table, %{
              expose_via_postgrest?: AshSupabase.Info.expose_via_postgrest?(resource),
              realtime?: AshSupabase.Info.realtime?(resource),
              rls_authenticated_select?: AshSupabase.Info.rls_authenticated_select?(resource)
            })

          :event_log ->
            SQL.event_log_statements(table)
        end

      {up ++ [{resource, table, res_up}], down ++ [{resource, table, res_down}]}
    end)
  end

  defp event_log_resources(otp_app) do
    otp_app
    |> Application.get_env(:ash_domains, [])
    |> Enum.flat_map(&Ash.Domain.Info.resources/1)
    |> Enum.uniq()
    |> Enum.filter(&(AshEvents.EventLog in Spark.extensions(&1)))
  end

  defp print_dry_run(repo, up, down) do
    Mix.shell().info("-- #{inspect(repo)} -- up --\n")
    Enum.each(up, fn {resource, table, stmts} -> print_group(resource, table, stmts) end)
    Mix.shell().info("\n-- #{inspect(repo)} -- down --\n")
    Enum.each(down, fn {resource, table, stmts} -> print_group(resource, table, stmts) end)
  end

  defp print_group(resource, table, stmts) do
    Mix.shell().info("-- #{inspect(resource)} (#{table})")
    Enum.each(stmts, &Mix.shell().info(&1 <> "\n"))
  end

  defp write_migration!(repo, up, down) do
    repo_name = repo |> Module.split() |> List.last() |> Macro.underscore()
    dir = Path.join(["priv", repo_name, "migrations"])
    timestamp = timestamp()
    module_name = Module.concat([repo, Migrations, :"AshSupabasePolicies#{timestamp}"])
    file = Path.join(dir, "#{timestamp}_ash_supabase_policies.exs")

    Mix.Generator.create_file(file, migration_source(module_name, up, down))
  end

  defp migration_source(module_name, up, down) do
    """
    defmodule #{inspect(module_name)} do
      @moduledoc \"\"\"
      Generated by `mix ash_supabase.gen_policies`. Locks every
      AshSupabase-managed table (and every AshEvents event log) so that
      only the role this repo connects as can write to it -- PostgREST's
      `anon`/`authenticated` roles get, at most, a read-only grant, and
      only for resources that opted in with `expose_via_postgrest? true`.

      Safe to re-run: every statement here is idempotent.
      \"\"\"

      use Ecto.Migration

      def up do
    #{format_statements(up)}
      end

      def down do
    #{format_statements(down)}
      end
    end
    """
  end

  defp format_statements(groups) do
    groups
    |> Enum.flat_map(fn {resource, table, stmts} ->
      ["    # #{inspect(resource)} (#{table})" | Enum.map(stmts, &execute_call/1)]
    end)
    |> Enum.join("\n\n")
  end

  defp execute_call(stmt) do
    "    execute(#{inspect(String.trim(stmt))})"
  end

  defp timestamp do
    {{y, mo, d}, {h, mi, s}} = :calendar.universal_time()
    "#{y}#{pad(mo)}#{pad(d)}#{pad(h)}#{pad(mi)}#{pad(s)}"
  end

  defp pad(i), do: i |> Integer.to_string() |> String.pad_leading(2, "0")
end
