defmodule AshSupabase.Test.Repo.Migrations.AshSupabasePolicies20260829190848 do
  @moduledoc """
  Generated by `mix ash_supabase.gen_policies`. Locks every
  AshSupabase-managed table (and every AshEvents event log) so that
  only the role this repo connects as can write to it -- PostgREST's
  `anon`/`authenticated` roles get, at most, a read-only grant, and
  only for resources that opted in with `expose_via_postgrest? true`.

  Safe to re-run: every statement here is idempotent.
  """

  use Ecto.Migration

  def up do
    # AshSupabase.Test.Todos.Todo (todos)

    execute("ALTER TABLE \"todos\" ENABLE ROW LEVEL SECURITY;")

    execute("REVOKE ALL ON \"todos\" FROM anon, authenticated;")

    execute("DO $$\nBEGIN\n  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN\n    CREATE PUBLICATION supabase_realtime;\n  END IF;\nEND $$;")

    execute("DO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM pg_publication_tables\n    WHERE pubname = 'supabase_realtime' AND tablename = 'todos'\n  ) THEN\n    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE \"todos\"';\n  END IF;\nEND $$;")

    # AshSupabase.Test.Events.Event (events)

    execute("ALTER TABLE \"events\" ENABLE ROW LEVEL SECURITY;")

    execute("REVOKE ALL ON \"events\" FROM anon, authenticated;")
  end

  def down do
    # AshSupabase.Test.Todos.Todo (todos)

    execute("DO $$\nBEGIN\n  IF EXISTS (\n    SELECT 1 FROM pg_publication_tables\n    WHERE pubname = 'supabase_realtime' AND tablename = 'todos'\n  ) THEN\n    EXECUTE 'ALTER PUBLICATION supabase_realtime DROP TABLE \"todos\"';\n  END IF;\nEND $$;")

    execute("ALTER TABLE \"todos\" DISABLE ROW LEVEL SECURITY;")

    # AshSupabase.Test.Events.Event (events)

    execute("ALTER TABLE \"events\" DISABLE ROW LEVEL SECURITY;")
  end
end
