defmodule AshSupabase.Test.Repo.Migrations.AddObligationsWelcome do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:obligations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :subject_id, :uuid, null: false
      add :owner_id, :uuid
      add :status, :text, null: false, default: "open"
      add :outcome_label, :text
      add :blocked_reason, :text
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:welcome_posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :minimum_coverage, :bigint, null: false
      add :current_coverage, :bigint, default: 0
    end
  end

  def down do
    drop table(:welcome_posts)

    drop table(:obligations)
  end
end
