defmodule AshSupabase.Test.Repo.Migrations.AshSupabasePolicies20260829200421 do
  @moduledoc """
  Generated by `mix ash_supabase.gen_policies`. Locks every
  AshSupabase-managed table (and every AshEvents event log) so that
  only the role this repo connects as can write to it -- PostgREST's
  `anon`/`authenticated` roles get, at most, a read-only grant, and
  only for resources that opted in with `expose_via_postgrest? true`.

  Safe to re-run: every statement here is idempotent.
  """

  use Ecto.Migration

  def up do
    # AshSupabase.Test.Todos.Todo (todos)

    execute("ALTER TABLE \"todos\" ENABLE ROW LEVEL SECURITY;")

    execute("REVOKE ALL ON \"todos\" FROM anon, authenticated;")

    execute("DO $$\nBEGIN\n  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN\n    CREATE PUBLICATION supabase_realtime;\n  END IF;\nEND $$;")

    execute("DO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM pg_publication_tables\n    WHERE pubname = 'supabase_realtime' AND tablename = 'todos'\n  ) THEN\n    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE \"todos\"';\n  END IF;\nEND $$;")

    # AshSupabase.Test.Receipts.Receipt (receipts)

    execute("ALTER TABLE \"receipts\" ENABLE ROW LEVEL SECURITY;")

    execute("REVOKE ALL ON \"receipts\" FROM anon, authenticated;")

    # AshSupabase.Test.Finance.Account (finance_accounts)

    execute("ALTER TABLE \"finance_accounts\" ENABLE ROW LEVEL SECURITY;")

    execute("REVOKE ALL ON \"finance_accounts\" FROM anon, authenticated;")

    execute("DO $$\nBEGIN\n  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN\n    CREATE PUBLICATION supabase_realtime;\n  END IF;\nEND $$;")

    execute("DO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM pg_publication_tables\n    WHERE pubname = 'supabase_realtime' AND tablename = 'finance_accounts'\n  ) THEN\n    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE \"finance_accounts\"';\n  END IF;\nEND $$;")

    # AshSupabase.Test.Obligations.Obligation (obligations)

    execute("ALTER TABLE \"obligations\" ENABLE ROW LEVEL SECURITY;")

    execute("REVOKE ALL ON \"obligations\" FROM anon, authenticated;")

    execute("DO $$\nBEGIN\n  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN\n    CREATE PUBLICATION supabase_realtime;\n  END IF;\nEND $$;")

    execute("DO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM pg_publication_tables\n    WHERE pubname = 'supabase_realtime' AND tablename = 'obligations'\n  ) THEN\n    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE \"obligations\"';\n  END IF;\nEND $$;")

    # AshSupabase.Test.Welcome.Post (welcome_posts)

    execute("ALTER TABLE \"welcome_posts\" ENABLE ROW LEVEL SECURITY;")

    execute("REVOKE ALL ON \"welcome_posts\" FROM anon, authenticated;")

    execute("DO $$\nBEGIN\n  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN\n    CREATE PUBLICATION supabase_realtime;\n  END IF;\nEND $$;")

    execute("DO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM pg_publication_tables\n    WHERE pubname = 'supabase_realtime' AND tablename = 'welcome_posts'\n  ) THEN\n    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE \"welcome_posts\"';\n  END IF;\nEND $$;")

    # AshSupabase.Test.Kids.StaffingRequirement (kids_staffing_requirements)

    execute("ALTER TABLE \"kids_staffing_requirements\" ENABLE ROW LEVEL SECURITY;")

    execute("REVOKE ALL ON \"kids_staffing_requirements\" FROM anon, authenticated;")

    execute("DO $$\nBEGIN\n  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN\n    CREATE PUBLICATION supabase_realtime;\n  END IF;\nEND $$;")

    execute("DO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM pg_publication_tables\n    WHERE pubname = 'supabase_realtime' AND tablename = 'kids_staffing_requirements'\n  ) THEN\n    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE \"kids_staffing_requirements\"';\n  END IF;\nEND $$;")

    # AshSupabase.Test.Federation.PartnerChurch (partner_churches)

    execute("ALTER TABLE \"partner_churches\" ENABLE ROW LEVEL SECURITY;")

    execute("REVOKE ALL ON \"partner_churches\" FROM anon, authenticated;")

    # AshSupabase.Test.Events.Event (events)

    execute("ALTER TABLE \"events\" ENABLE ROW LEVEL SECURITY;")

    execute("REVOKE ALL ON \"events\" FROM anon, authenticated;")
  end

  def down do
    # AshSupabase.Test.Todos.Todo (todos)

    execute("DO $$\nBEGIN\n  IF EXISTS (\n    SELECT 1 FROM pg_publication_tables\n    WHERE pubname = 'supabase_realtime' AND tablename = 'todos'\n  ) THEN\n    EXECUTE 'ALTER PUBLICATION supabase_realtime DROP TABLE \"todos\"';\n  END IF;\nEND $$;")

    execute("ALTER TABLE \"todos\" DISABLE ROW LEVEL SECURITY;")

    # AshSupabase.Test.Receipts.Receipt (receipts)

    execute("ALTER TABLE \"receipts\" DISABLE ROW LEVEL SECURITY;")

    # AshSupabase.Test.Finance.Account (finance_accounts)

    execute("DO $$\nBEGIN\n  IF EXISTS (\n    SELECT 1 FROM pg_publication_tables\n    WHERE pubname = 'supabase_realtime' AND tablename = 'finance_accounts'\n  ) THEN\n    EXECUTE 'ALTER PUBLICATION supabase_realtime DROP TABLE \"finance_accounts\"';\n  END IF;\nEND $$;")

    execute("ALTER TABLE \"finance_accounts\" DISABLE ROW LEVEL SECURITY;")

    # AshSupabase.Test.Obligations.Obligation (obligations)

    execute("DO $$\nBEGIN\n  IF EXISTS (\n    SELECT 1 FROM pg_publication_tables\n    WHERE pubname = 'supabase_realtime' AND tablename = 'obligations'\n  ) THEN\n    EXECUTE 'ALTER PUBLICATION supabase_realtime DROP TABLE \"obligations\"';\n  END IF;\nEND $$;")

    execute("ALTER TABLE \"obligations\" DISABLE ROW LEVEL SECURITY;")

    # AshSupabase.Test.Welcome.Post (welcome_posts)

    execute("DO $$\nBEGIN\n  IF EXISTS (\n    SELECT 1 FROM pg_publication_tables\n    WHERE pubname = 'supabase_realtime' AND tablename = 'welcome_posts'\n  ) THEN\n    EXECUTE 'ALTER PUBLICATION supabase_realtime DROP TABLE \"welcome_posts\"';\n  END IF;\nEND $$;")

    execute("ALTER TABLE \"welcome_posts\" DISABLE ROW LEVEL SECURITY;")

    # AshSupabase.Test.Kids.StaffingRequirement (kids_staffing_requirements)

    execute("DO $$\nBEGIN\n  IF EXISTS (\n    SELECT 1 FROM pg_publication_tables\n    WHERE pubname = 'supabase_realtime' AND tablename = 'kids_staffing_requirements'\n  ) THEN\n    EXECUTE 'ALTER PUBLICATION supabase_realtime DROP TABLE \"kids_staffing_requirements\"';\n  END IF;\nEND $$;")

    execute("ALTER TABLE \"kids_staffing_requirements\" DISABLE ROW LEVEL SECURITY;")

    # AshSupabase.Test.Federation.PartnerChurch (partner_churches)

    execute("ALTER TABLE \"partner_churches\" DISABLE ROW LEVEL SECURITY;")

    # AshSupabase.Test.Events.Event (events)

    execute("ALTER TABLE \"events\" DISABLE ROW LEVEL SECURITY;")
  end
end
