defmodule AshSupabase.Test.Repo.Migrations.Init do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:events, primary_key: false) do
      add(:id, :bigserial, null: false, primary_key: true)
      add(:record_id, :uuid, null: false)
      add(:version, :bigint, null: false, default: 1)
      add(:metadata, :map, null: false, default: %{})
      add(:data, :map, null: false, default: %{})
      add(:changed_attributes, :map, null: false, default: %{})
      add(:occurred_at, :utc_datetime_usec, null: false)
      add(:resource, :text, null: false)
      add(:action, :text, null: false)
      add(:action_type, :text, null: false)
      add(:user_id, :uuid)
    end

    create table(:todos, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text, null: false)
      add(:completed, :boolean, default: false)
      add(:user_id, :uuid, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:users, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:todos) do
      modify(
        :user_id,
        references(:users, column: :id, name: "todos_user_id_fkey", type: :uuid, prefix: "public")
      )
    end

    alter table(:users) do
      add(:email, :text, null: false)
      add(:role, :text, default: "authenticated")
    end
  end

  def down do
    alter table(:users) do
      remove(:role)
      remove(:email)
    end

    drop(constraint(:todos, "todos_user_id_fkey"))

    alter table(:todos) do
      modify(:user_id, :uuid)
    end

    drop(table(:users))

    drop(table(:todos))

    drop(table(:events))
  end
end
