defmodule AshSupabase.Test.Repo.Migrations.AddKidsFederation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:kids_staffing_requirements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :service_name, :text, null: false
      add :required_workers, :bigint, null: false
      add :local_available_workers, :bigint, null: false
      add :fulfilled_workers, :bigint, default: 0
      add :status, :text, default: "open"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:partner_churches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :qualified_available_workers, :bigint, null: false
      add :verified_safeguarding, :boolean, null: false, default: false
      add :distance_miles, :bigint, null: false
      add :reserved_workers, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:partner_churches)

    drop table(:kids_staffing_requirements)
  end
end
