defmodule AshSupabase.Test.Repo.Migrations.AddFinanceReceipts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:finance_accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :kind, :text, null: false
      add :balance_cents, :bigint, default: 0
      add :owner_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:receipts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :subject_type, :text, null: false
      add :subject_id, :text, null: false
      add :ontology_version, :text, null: false
      add :policy_id, :text
      add :actor_type, :text
      add :actor_id, :text
      add :request_id, :text, null: false
      add :process, :text, null: false
      add :admission, :text, null: false
      add :outcome, :text, null: false
      add :refusal_type, :text
      add :source_state_version, :bigint
      add :state_version, :bigint
      add :events_created, :bigint, default: 0
      add :financial_postings, {:array, :map}, default: []
      add :notification_ids, {:array, :text}, default: []
      add :replay_identity, :map, default: %{}
      add :zero_write_verified, :boolean, default: false
      add :metadata, :map, default: %{}

      add :occurred_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:receipts)

    drop table(:finance_accounts)
  end
end
